[project]
name = "dm-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dmpython>=2.5.26",
    "fastmcp>=2.0.0",
    "hypothesis>=6.148.7",
]

[dependency-groups]
dev = [
    "hypothesis>=6.148.7",
    "pytest>=9.0.2",
]
